image: node:16

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm install --legacy-peer-deps
          - npm run build
          - npm run test-react
